language: nix

sudo: true

git:
  depth: 5

env:
  global:
  matrix:
    - GHCVERSION=ghc802
    - GHCVERSION=ghc822
    - GHCVERSION=ghc843

matrix:
  allow_failures:
  exclude:

script:
  - nix-build --argstr compiler $GHCVERSION
  - (cd bindings-posix ; nix-build --argstr compiler $GHCVERSION)
  - (cd bindings-gpgme ; nix-build --argstr compiler $GHCVERSION)
